### PR TITLE
Add TestCases::full_build() to force full builds.

### PR DESCRIPTION
**Pull request by de-vri-es**
Currently, `trybuild` uses `cargo check` for compile-fail tests, and only uses `cargo-build` if there are pass tests.

Some build failures are not detected by `cargo check`, but only by `cargo build`. This is arguably a problem of `cargo check`, but it is the current reality and as far as I can tell, unlikely to change soon.

People using `trybuild` are now adding an empty pass tests to work around this problem. While this works, it also clutters the output with `[should pass]` and `[should fail to compile]`.

This PR is a very simple addition to the API that allows users to opt-in to using `cargo build` for all tests, without cluttering the output.

Since `trybuild` is all about verifying compile failures, being able to verify failed const-evaluated assertions seems like a pretty important use case. And, as noted before (https://github.com/dtolnay/trybuild/issues/225#issuecomment-2272560055), the availability of `const { }` blocks lifted this use case out of the realm of unreliable hacks.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
My preference in https://github.com/dtolnay/trybuild/issues/258 is for this to be handled by a different library (maybe along with some other feature requests labeled https://github.com/dtolnay/trybuild/labels/out%20of%20scope). This crate is only doing what I need.

**Comment by de-vri-es** [comment]
Hmm, I don't want to nag, but could you reconsider?

At the moment this is the best library for validating compilation failures (I think). I would hate for such a simple change to require forking the crate, but I really need support for verifying `const { assert!(...) }`.

If the answer is still "no" I guess I will fork and try to think of another clever name :(

**Comment by golddranks** [comment]
Maybe fork with name willitbuild, as a reference to the "Will It Blend" commercials? As you can see from the linked issue that was deemed https://github.com/dtolnay/trybuild/labels/out%20of%20scope, I was also interested in this functionality.

**Comment by golddranks** [comment]
It should be noted, that since Rust 1.79, `const` blocks are stable, and `assert!()` in const has been stable for a while. It's becoming more and more common to have static assertions against type sizes, associated consts of generic types etc. This crate is not going to help catching tests of those compile errors, which means it's going to get more and more irrelevant over time without this support. I think @dtolnay should indeed reconsider.

**Pull request closed without merging**
