### PR TITLE
Check that tests exist before trying to build them

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I encountered this bug recently in my fork (which adds inline tests and sub-checks): the first time tests are run, they fail because they don't exist. The bug is actually present in your version as well, it's just not as bad as in my fork since the tests are supposed to already exist in your case.

So this fix simply moves the check of the tests existence before trying to build them.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
I am not clear on what this is fixes. Could you share a way that I could reproduce the incorrect behavior?

**Comment by GuillaumeGomez** [comment]
Add multiple tests with one that doesn't exist. You'll get the cargo error before you'll get the `check_exists` error, making the call to `check_exists` useless in `run_all`.

**Comment by GuillaumeGomez** [comment]
I'll write how to reproduce then:

1. Use https://crates.io/crates/trybuild2 (which doesn't include the equivalent fix of this PR that you can see [here](https://github.com/GuillaumeGomez/trybuild2/pull/4))
2. Clone https://github.com/gtk-rs/gtk-rs-core locally
3. Go to `glib-macros` subfolder
4. Run `cargo test clone_failures` (which you can see [here](https://github.com/gtk-rs/gtk-rs-core/blob/master/glib-macros/tests/clone.rs#L259))

On the first run, the tests won't exist (because they need to be generated) and on the first run it'll work. It illustrates what this PR fixes: `check_exists` is called **after** the cargo run, making it either useless or too late.

**Comment by dtolnay** [comment]
That repro doesn't even involve this crate.

I am going to assume this fix is not relevant to this crate.

**Comment by GuillaumeGomez** [comment]
It is but whatever... Thanks in any case for writing this crate.

**Comment by GuillaumeGomez** [comment]
For completeness:

1. You run all tests https://github.com/dtolnay/trybuild/blob/master/src/run.rs#L346
2. You check all tests exist (9 lines below) https://github.com/dtolnay/trybuild/blob/master/src/run.rs#L355

**Pull request closed without merging**
