### PR TITLE
Add functionalities

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
It makes runtime generated tests possible more easily like this. :)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
What you're asking is litterally impossible... Also: why preventing the add of new API? I added them in order to keep the current one unchanged so people using `trybuild` wouldn't need to change anything.

**Comment by GuillaumeGomez** [comment]
What you're asking is litterally impossible... Also: why preventing the add of new API? I added them in order to keep the current one unchanged so people using `trybuild` wouldn't need to change anything.

**Comment by CreepySkeleton** [comment]
@GuillaumeGomez Could you please elaborate on why you think generated tests are impossible? Just write them into files in `OUT_DIR` and direct `trybuild` there.

**Comment by GuillaumeGomez** [comment]
It's not impossible, just very ugly. I don't want to have to handle temporary files. Also, you can't generate stderr just like that (which is why I added the sub-string check), making this with the current API if not impossible, very complicated.

**Pull request closed without merging**
