### PR TITLE
Replace file locking logic with subdirectory

### PR DESCRIPTION
**Pull request by neysofu**
Hi, thanks for `trybuild`! I use all the time, and it's great.

Sometimes, when I throw a lot of `#[test]`s at `trybuild`, I notice that they take a really long time. It seems that it's because they all run serially and not in parallel. I was thinking it might be better to create a separate directory per `Runner` and remove locking altogether, which would improve throughput.

### CODE REVIEW

**Comment by neysofu** [comment]
My new approach creates a temporary directory for each `Project`, removing the need for `cargo clean` as well.

**Comment by dtolnay** [comment]
Is the 36s project open source? I am interested to assess how problematic it might be for the output from concurrent tests to be interleaved.

**Comment by neysofu** [comment]
Yes, you can take a look here: https://github.com/Sovereign-Labs/sovereign-sdk/tree/filippo/trybuild-repro.

The timings you'll get are different from the ones I gave you because I originally ran my benchmarks against a private version of the codebase which has significant changes. But you'll notice the tests still take longer without the patch regardless.

Steps to reproduce:
1. `cargo nextest run -p sov-modules-macros`
2. `cargo nextest run -p sov-modules-macros` (cached)
3. Apply the `trybuild` patch at the root `Cargo.toml`
4. `cargo nextest run -p sov-modules-macros`
5. `cargo nextest run -p sov-modules-macros` (cached)

I get similar results with `cargo test` instead of `cargo nextest`.

**Comment by dtolnay** [comment]
The vast majority of the time in your tests is being spent in the linker, because you are linking over 200 megabytes of dependencies into every individual test case.

What I would recommend is: stick to only `compile_fail` tests. Move your `pass` tests somewhere else and build them with Cargo as an integration test instead of trybuild. Then consolidate all the `compile_fail` tests into one TestCases. Trybuild will perform _all_ the compilation in parallel, and will bypass linking. You should find that it is an order of magnitude faster than what you got with this PR.

**Comment by neysofu** [comment]
Thanks for the great suggestions. Just wondering though, what's the problem with the temporary directory approach? Naively, I assumed it would make things better for other use cases as well compared to locking.

**Comment by dtolnay** [comment]
For my own use cases, this doesn't end up being an improvement. I think the most number of UI test cases I have in one project is Serde which has 101 currently, and the compilation of all of them takes only 330ms. In my other projects it's even less. So I'd rather have the generated Cargo.toml around for troubleshooting, than what this PR does with temporary directories.

**Pull request closed without merging**
